#=================================================#
#                                                 #
#               Luma Database                #
#                                                 #
#=================================================#
MONGO:
  HOST: 127.0.0.1
  PORT: 27017
  DATABASE: 'Luma'
  AUTHENTICATION:
    ENABLED: false
    USERNAME: root
    PASSWORD: ''
    DATABASE: 'admin'